### ISSUE TITLE
Question: What about keyword focus and analysis?

### ISSUE THREAD

**Issue by beatelite** [thierrypigot/beaver-builder-toolbox#2]
Have you attempted to get the keyword focus and content analysis for yoast seo in the page settings yet? 

did you have any issues with it if you made an attempt?

Thinking about pulling and seeing if I can make it work but wanted to see if you ran into any gotchas that I should be armed with before I do. 

Yoast is moving to realtime analysis so it would be cool to see it work with this.

**Comment by thierrypigot** [comment]
Focus keyword is really not useful and is a bad way in seo strategy. In SEO you have to be concentrated on the single thematic and not on a single keyword. Have a green light not mean you have made the good SEO work.
